language: php
before_install:
  - pip install --user codecov
script:
    - phpunit --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"  