language: php
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
language: php
before_install:
  - pip install --user codecov
script:
    - phpunit --coverage-clover=coverage.xml
after_success:
    - codecov --token=525c3a38-f2c4-4b56-9f98-435db3190079
#  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"