language: php

php:
- 5.5

addons:
    code_climate:
        repo_token: 6cef356f8bc0802a667d2d49cb8498a3da90eedf9f24d61b7f6984fb60195f18
 
after_script:
  - vendor/bin/test-reporter
  
before_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
   
script: phpunit -h

before_install:
  - pip install --user codecov
after_success:
  - codecov --token=525c3a38-f2c4-4b56-9f98-435db3190079
#script: phpunit --coverage-clover=coverage.clover
