language: php
script: 
  - vendor/bin/phpunit --coverage-clover=coverage.xml


after_success:
    - bash <(curl -s https://codecov.io/bash)
    
addons:
    code_climate:
        repo_token: 6cef356f8bc0802a667d2d49cb8498a3da90eedf9f24d61b7f6984fb60195f18
