language: php
php:
    - 5.3
    - 5.3.29
    - 5.3.3
    - 5.4
    - 5.4.37
    - 5.5
    - 5.5.21
    - 5.5.9
    - 5.6
    - 5.6.5
    - hhvm
    - hhvm-3.5.0~precise
#    - hhvm-nightly #HHVM nightly is no longer supported on Ubuntu Precise. https://github.com/travis-ci/travis-ci/issues/3788
language: php
before_install:
    - composer require codeclimate/php-test-reporter --dev
    - composer self-update
    - pip install --user codecov
before_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
script:
    - phpunit --coverage-clover build/logs/clover.xml
    - phpunit --coverage-clover=coverage.xml
    - phpunit --coverage-clover=coverage.clover
after_script:
#    - vendor/bin/test-reporter
  - CODECLIMATE_REPO_TOKEN="28e9cda98834018e04d33a12cd700aa7771bc4705eb2fdd0f32c56da73fbbb1e" bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
after_success:
    - codecov --token=525c3a38-f2c4-4b56-9f98-435db3190079
addons:
    code_climate:
        repo_token: 28e9cda98834018e04d33a12cd700aa7771bc4705eb2fdd0f32c56da73fbbb1e