language: php
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
language: php
before_install:
  - pip install --user codecov
before_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
script:
    - phpunit --coverage-clover=coverage.xml
    - phpunit --coverage-clover=coverage.clover
after_success:
    - codecov --token=525c3a38-f2c4-4b56-9f98-435db3190079
#  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"




#after_script:
#  - vendor/bin/test-reporter
  

   
