language: php

php:
- 5.6

sudo: required

addons:
    code_climate:
        repo_token: 6cef356f8bc0802a667d2d49cb8498a3da90eedf9f24d61b7f6984fb60195f18

install:
    pip install codecov
after_success:
    codecov
